### ISSUE TITLE
Broken links in pod of DAVECROSS/Perlanet-v3.0.2 /bin/perlanet

### ISSUE THREAD

**Issue by guest20** [davorg/perlanet#22]
See Also: https://metacpan.org/release/DAVECROSS/Perlanet-v3.0.2/view/bin/perlanet

# `wiki.github.com` seems to just 500. 
The links in the pod take the reader to a github error page:

<img width="456" alt="Screen Shot 2023-05-22 at 10 26 16" src="https://github.com/davorg/perlanet/assets/3603869/f7b2cd71-8735-44fe-9519-eb0d0c491fd3">

Either it's just a blip and I got lucky, or github wants folks to update their urls to per-project `/wiki` urls:

http://wiki.github.com/davorg/perlanet -> http://github.com/davorg/perlanet/wiki

**Comment by davorg** [comment]
Thanks for the reports. I've fixed those links in v3.0.3 - which is en route to CPAN right now.

**Comment by guest20** [comment]
Reporting issues on cpan dists: it's either 21 years or 21 minutes

**Comment by davorg** [comment]
Perlanet v3.0.3 is now on CPAN - https://metacpan.org/release/DAVECROSS/Perlanet-v3.0.3
