### ISSUE TITLE
Empty atom.xml

### ISSUE THREAD

**Issue by davehodg** [davorg/perlanet#9]
This is possibly a stupid question. I have a perlanetrc that parses, and it appears to go out and request other RSS feeds. A few fail with "Attribute (_xml_feed) does not pass the type constraint".
Eventually, it produces an atom.xml and .html with no content.

How do I diagnose this? Or just make it work?

**Comment by davehodg** [comment]
Forget it, I think I know.

**Comment by davorg** [comment]
If you need any more help, please attach the `perlanetrc`.

**Comment by davehodg** [comment]
My fault, it was a braino.

My next question is, why can't there be a standard for referencing an RSS feed?! I've got three whose web page HTML gives no clue, but feedly seems quite happy.

**Comment by davorg** [comment]
XML::Feed has a `find_feeds()` method (which just uses `Feed::Find`). But Perlanet doesn't use that as I always thought it was safer to give it the feed URI.

**Comment by davehodg** [comment]
Any clue about these three?

https://www.hp-lexicon.org/category/podcasts/harry-potter-minute/
https://www.potterlesspodcast.com/
https://www.swishflickcast.com/pages/meet-your-hosts

**Comment by davehodg** [comment]
Never mind. Export OPML did the job.

**Comment by davehodg** [comment]
Feedly got one of the three. One only has an iTunes feed. The other has nothing.

**Comment by davehodg** [comment]
Do you not follow redirects? Yes, I know. Stupid.

**Comment by davorg** [comment]
It's a standard LWP::UserAgent object. So it follows redirects on `GET` and `HEAD`.  But you could use `LWP::UserAgent::requests_redirectable()` to change that.

**Comment by davehodg** [comment]
Weird. Perlanet warned me and didn't follow the redirect. Never mind, I did in configs.

**Comment by davehodg** [comment]
Possible final one. Perlanet works from the command line. In contab as:
`42 */4 * * * (perlbrew switch perl-5.30.1 ; cd /home/daveh/pottercasts ; /root/perl5/perlbrew/perls/perl-5.30.1/bin/perlanet)
`
Gives me:

`Return-Path: <root@polarbear.vs.mythic-beasts.com>
Received: from polarbear.vs.mythic-beasts.com (localhost [127.0.0.1])
	by polarbear.vs.mythic-beasts.com (8.15.2/8.15.2/Debian-10) with ESMTP i
d 01RGg17H006802
	for <root@polarbear.vs.mythic-beasts.com>; Thu, 27 Feb 2020 16:42:01 GMT
Received: (from root@localhost)
	by polarbear.vs.mythic-beasts.com (8.15.2/8.15.2/Submit) id 01RGg1xD0068
01
	for root; Thu, 27 Feb 2020 16:42:01 GMT
Date: Thu, 27 Feb 2020 16:42:01 GMT
Message-Id: <202002271642.01RGg1xD006801@polarbear.vs.mythic-beasts.com>
From: root@polarbear.vs.mythic-beasts.com (Cron Daemon)
To: root@polarbear.vs.mythic-beasts.com
Subject: Cron <root@polarbear> (perlbrew switch perl-5.30.1 ; cd /home/daveh/pot
tercasts ; /root/perl5/perlbrew/perls/perl-5.30.1/bin/perlanet)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>


A sub-shell is launched with perl-5.30.1 as the activated perl. Run 'exit' to fi
nish it.

Can't locate Perlanet/Simple.pm in @INC (you may need to install the Perlanet::S
imple module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.2
6.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share
/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/s
ite_perl /usr/lib/x86_64-linux-gnu/perl-base) at /root/perl5/perlbrew/perls/perl
-5.30.1/bin/perlanet line 6.
BEGIN failed--compilation aborted at /root/perl5/perlbrew/perls/perl-5.30.1/bin/
perlanet line 6.`

**Comment by davorg** [comment]
That seems to be a problem with your environment. It looks like `@INC` is set wrong for the version of Perl you're using.

**Comment by davehodg** [comment]
I would have thought perlbrew switch would have taken care of that. Unless it's running the system perl.

**Comment by davorg** [comment]
I would have thought so too. But I think your problem is with perlbrew rather than perlanet. The perlanet shebang uses `env perl` so it should work with perlbrew.

**Comment by davehodg** [comment]
OK cron is:

> A sub-shell is launched with perl-5.30.1 as the activated perl. Run 'exit' to fi
nish it.
> /usr/bin/perl

The system perl is 5.26. I think I'll use that.

**Comment by davehodg** [comment]
Not impressed with Feed::Find. I've not got it to work yet. And I've got 70 feeds to find!

**Comment by davorg** [comment]
Looks like there's no actual outstanding Perlanet bug here.
